import { useState } from "react";

export function AnonimousComponent(props) {
  const [count, setCount] = useState(0);

  return (
    <div>
      This is generated by a high order function {count}
      <div>
        <input
          value={props.value}
          onChange={(e) => {
            props.setText(e.target.value);
          }}
        ></input>
      </div>
      <div>
        <button
          onClick={() => {
            setCount(count + 1);
          }}
        >
          increment by 1
        </button>
      </div>
      {props.children}
    </div>
  );
}
